force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Resource__c/Project_Resource__c.object-meta.xml
<CustomObject>
    <label>Project Resource</label>
    <nameField>
        <label>Project Resource Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Resources</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Resource__c/fields/ProjectLineItem__c.field-meta.xml
<CustomField>
    <fullName>ProjectLineItem__c</fullName>
    <label>ProjectLineItem</label>
    <referenceTo>ProjectLineItem__c</referenceTo>
    <relationshipLabel>Project Resources</relationshipLabel>
    <relationshipName>Project_Resources</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Project_Resource__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Project_Resources</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProjectLineItem__c/ProjectLineItem__c.object-meta.xml
<CustomObject>
    <label>ProjectLineItem</label>
    <nameField>
        <label>ProjectLineItem Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ProjectsLineItem</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ProjectLineItem__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>ProjecstLineItem</relationshipLabel>
    <relationshipName>ProjecstLineItem</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ProjectResourceTriggerHelper.cls
public with sharing class ProjectResourceTriggerHelper {

    public static void BeforeInsert(List<Project_Resource__c> projectResourses){
        Map<Id, Project_Resource__c> newProjectResourceMap = new Map<Id, Project_Resource__c>();
        Id PLI = projectResourses[0].ProjectLineItem__c;
               
        for(Project_Resource__c pr :projectResourses){
            newProjectResourceMap.put(pr.Resource__c, pr);
        }
    
        ProjectLineItem__c project = [SELECT Project__r.StartDate__c, Project__r.EndDate__c FROM ProjectLineItem__c WHERE Id =: PLI];
        Date StartProject = project.Project__r.StartDate__c; 
        Date EndProject = project.Project__r.EndDate__c;
    
        List<Project_Resource__c> oldProjectResourcesList = [SELECT Id, StartDate__c, EndDate__c, Resource__c FROM Project_Resource__c WHERE Resource__c IN : newProjectResourceMap.keySet()];
    
        Map<Id, List<Project_Resource__c>> oldProjectResourceMap = new Map<Id, List<Project_Resource__c>>();
    
        for(Project_Resource__c pr :oldProjectResourcesList){
            if(oldProjectResourceMap.containsKey(pr.Resource__c)){
                oldProjectResourceMap.get(pr.Resource__c).add(pr);
            } else{
                oldProjectResourceMap.put(pr.Resource__c, new List<Project_Resource__c>{pr});
            }
        }    
    
        List<Project_Resource__c> readyForInsert = new List<Project_Resource__c>();
    
        for(Id key :newProjectResourceMap.keySet()){
    
            if(newProjectResourceMap.get(key).StartDate__c >= project.Project__r.StartDate__c && newProjectResourceMap.get(key).EndDate__c <= project.Project__r.EndDate__c){
    
            if(oldProjectResourceMap.containsKey(key)){
                
                for(Project_Resource__c pr :oldProjectResourceMap.get(key)){
    
                        if(newProjectResourceMap.get(key).StartDate__c < pr.StartDate__c && newProjectResourceMap.get(key).EndDate__c < pr.StartDate__c || newProjectResourceMap.get(key).StartDate__c > pr.EndDate__c && newProjectResourceMap.get(key).EndDate__c > pr.EndDate__c){
    
                            readyForInsert.add(newProjectResourceMap.get(key));
                        } else{
                            newProjectResourceMap.get(key).addError('The resource ' + newProjectResourceMap.get(key).Name + ' is allocated in another project on these Dates');
                        }
                    }
                } 
            }
            else{
                newProjectResourceMap.get(key).addError('The dates assigned dont match to the dates of the project');
               
            }
        }        
    } 
}