force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pre-Kickoff</fullName>
                <default>true</default>
                <label>Pre-Kickoff</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ResourceTask__c/ResourceTask__c.object-meta.xml
<CustomObject>
    <label>Resource Task</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ResourceTask__c/fields/AproximateHours__c.field-meta.xml
<CustomField>
    <fullName>AproximateHours__c</fullName>
    <label>AproximateHours</label>
    <precision>4</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ResourceTask__c/fields/InProgress__c.field-meta.xml
<CustomField>
    <fullName>InProgress__c</fullName>
    <formula>IF( ISPICKVAL( Status__c , &apos;In Progress&apos;) , true, false)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>In Progress</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ResourceTask__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Tasks</relationshipLabel>
    <relationshipName>ResourceTasks</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ResourceTask__c/fields/RegisteredHours__c.field-meta.xml
<CustomField>
    <fullName>RegisteredHours__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Registered Hours</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ResourceTask__c/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <label>StartDate</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ResourceTask__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No Initiated</fullName>
                <default>true</default>
                <label>No Initiated</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/GetTask.cls
public with sharing class GetTask {
    @AuraEnabled(cacheable = true)
    public static Map<String, List<ResourceTask__c>> getTaskByUser (){
        List<ResourceTask__c> tasksList = [SELECT Project__r.Name, Name, Status__c, AproximateHours__c, RegisteredHours__c, StartDate__c, InProgress__c
         FROM ResourceTask__c WHERE OwnerId =: UserInfo.getUserId() AND Status__c != 'Completed' ORDER BY  Status__c DESC, StartDate__c];

        Map<String, List<ResourceTask__c>> taskListByProjectMap = new Map<String, List<ResourceTask__c>>();

        for(ResourceTask__c tsk: tasksList){
            if(taskListByProjectMap.containsKey(tsk.Project__r.Name)){
                taskListByProjectMap.get(tsk.Project__r.Name).add(tsk);
            } else{
                taskListByProjectMap.put(tsk.Project__r.Name, new List<ResourceTask__c>{tsk});
            }
        }
        return taskListByProjectMap;
    }
}