force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Resource__c/Project_Resource__c.object-meta.xml
<CustomObject>
    <label>Project Resource</label>
    <nameField>
        <label>Project Resource Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Resources</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Resource__c/fields/ProjectLineItem__c.field-meta.xml
<CustomField>
    <fullName>ProjectLineItem__c</fullName>
    <label>ProjectLineItem</label>
    <referenceTo>ProjectLineItem__c</referenceTo>
    <relationshipLabel>Project Resources</relationshipLabel>
    <relationshipName>Project_Resources</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Project_Resource__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Project_Resources</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project_Resource__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Developer</fullName>
            </value>
            <value>
                <fullName>Architect</fullName>
            </value>
            <value>
                <fullName>Consultant</fullName>
            </value>
            <value>
                <fullName>ProjectManager</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ProjectLineItem__c/ProjectLineItem__c.object-meta.xml
<CustomObject>
    <label>ProjectLineItem</label>
    <nameField>
        <label>ProjectLineItem Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ProjectsLineItem</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ProjectLineItem__c/fields/CoveredHours__c.field-meta.xml
<CustomField>
    <fullName>CoveredHours__c</fullName>
    <formula>Quantity__c -  ResourceHours__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>HoursLeftToCover</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ProjectLineItem__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>ProjecstLineItem</relationshipLabel>
    <relationshipName>ProjecstLineItem</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ProjectLineItem__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Consultant</fullName>
            </value>
            <value>
                <fullName>Developer</fullName>
            </value>
            <value>
                <fullName>Architect</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Rateph__c.field-meta.xml
<CustomField>
    <fullName>Rateph__c</fullName>
    <label>Rateph</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/User/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <formula>UserRole.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Role</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/GetRolesWithUsers.cls
public with sharing class GetRolesWithUsers {
    @AuraEnabled
    public static void metodoX ( Id projectId , string resourcesMap  ) {
    system.debug(resourcesMap + ' '+ projectId );
    Map<Id,list<date>> resourcebymap = (Map<Id, list<date>>)JSON.deserializeStrict( resourcesMap, Map<Id, list<date>>.class);
     Project__c proyect =[SELECT name,(SELECT Role__c,Id FROM ProjecstLineItem__r WHERE Project__c =: projectId) FROM Project__c
      WHERE Id =: projectId];
    
     map<string,id> RolbyPliId =new map<string,id>();
         for(ProjectLineItem__c PLI : proyect.ProjecstLineItem__r){
             RolbyPliId.put(PLI.Role__c, PLI.Id);
         }
 
    
     list<user> ListResource=[SELECT Role__c,Name FROM user WHERE Id in: resourcebymap.keySet()];
 
         list <Project_Resource__c> listProyectResource = new list <Project_Resource__c>();
 
         for (user resource : ListResource){
             
             listProyectResource.add(new Project_Resource__c (
                 Resource__c = resource.Id,
                 name = resource.name,
                 projectLineItem__c= RolbyPliId.get(resource.role__c),
                 StartDate__c=resourcebymap.get(resource.Id)[0],
                 endDate__c=resourcebymap.get(resource.Id)[1],
                 role__c=resource.role__c
             ));
         }
         system.debug('list ' + listProyectResource );
         insert listProyectResource;
         
     }

    public class ProjectWrapper{
        @AuraEnabled
        public List<ProjectLineItem__c> roles = new List<ProjectLineItem__c>(); 

        @AuraEnabled
        public Map<String, List<User>> resources = new Map<String, List<User>>();
        
        public ProjectWrapper(List<ProjectLineItem__c> roles, Map<String, List<User>> resources){
            this.roles = roles;
            this.resources = resources;
        }
    }

    @AuraEnabled(cacheable=true)
    public static ProjectWrapper getProjectWrapper(Id projectId){
        ProjectWrapper wrapper = new ProjectWrapper(getProjectRoles(projectId), getResourcesByRole(projectId));

        return wrapper;
    }
    
    public static List<ProjectLineItem__c> getProjectRoles(Id projectId){
        List<ProjectLineItem__c> projectLineItem = [SELECT Id, Role__c, CoveredHours__c FROM ProjectLineItem__c WHERE Project__c =: projectId];

        return projectLineItem;
    }

    public static Map<String, List<User>> getResourcesByRole(Id projectId){
        List<ProjectLineItem__c> projectLineItem = getProjectRoles(projectId);

        Set<String> roles = new Set<String>();
        for(ProjectLineItem__c pli: projectLineItem){
            roles.add(pli.Role__c);
        }

        Project__c project = [SELECT Id, Name, StartDate__c, EndDate__c FROM Project__c WHERE Id =: projectId];
       
        Date startDate = project.StartDate__c;
        Date endDate = project.EndDate__c;

        List<User> usersListByRole = [SELECT Id, Name, Role__c, Rateph__c, (SELECT StartDate__c, EndDate__c, ProjectLineItem__r.Project__c FROM Project_Resources__r WHERE (StartDate__c >=:startDate AND StartDate__c <=: endDate) OR (EndDate__c >=:startDate AND EndDate__c <=: endDate )) FROM User WHERE Role__c IN: roles];

        Map<String, List<User>> resourcesByRole = new Map<String, List<User>>();

        for(User resource: usersListByRole){
            if(resource.Project_Resources__r.size() == 0){
                if(resourcesByRole.containsKey(resource.Role__c)){
                    resourcesByRole.get(resource.Role__c).add(resource);
                } else{
                    resourcesByRole.put(resource.Role__c, new List<User>{resource});
                }
            }
            if(resource.Project_Resources__r.size() == 1){
                if(startDate.daysBetween(resource.Project_Resources__r[0].StartDate__c) >= 1 || resource.Project_Resources__r[0].EndDate__c.daysBetween(endDate) >= 1){
                    if(resourcesByRole.containsKey(resource.Role__c)){
                        resourcesByRole.get(resource.Role__c).add(resource);
                    } else{
                        resourcesByRole.put(resource.Role__c, new List<User>{resource});
                    }
                }
            } else{
                for(Project_Resource__c proResource: resource.Project_Resources__r){

                    Integer currentIterationIndex = resource.Project_Resources__r.indexOf(proResource);

                    Date iterationStartDate = proResource.StartDate__c;
                    Date iterationEndDate = proResource.EndDate__c;

                    if(currentIterationIndex == 0 && startDate.daysBetween(iterationStartDate) >= 1){

                        if(resourcesByRole.containsKey(resource.Role__c)){
                            resourcesByRole.get(resource.Role__c).add(resource);
                        } else{
                            resourcesByRole.put(resource.Role__c, new List<User>{resource});
                        }
                    } else if(currentIterationIndex != 0 && (currentIterationIndex + 1) != resource.Project_Resources__r.size()){
                        Integer previousIterationIndex = resource.Project_Resources__r.indexOf(proResource);
                        previousIterationIndex -= 1;

                        Date previousIterationEndDate = resource.Project_Resources__r[previousIterationIndex].EndDate__c;

                        if(previousIterationEndDate.daysBetween(iterationStartDate) >= 1){
                            if(resourcesByRole.containsKey(resource.Role__c)){
                                resourcesByRole.get(resource.Role__c).add(resource);
                            } else{
                                resourcesByRole.put(resource.Role__c, new List<User>{resource});
                            }
                        }
                    } else if((currentIterationIndex + 1) == resource.Project_Resources__r.size()){
                        Integer previousIterationIndex = resource.Project_Resources__r.indexOf(proResource);
                        previousIterationIndex -= 1;

                        Date previousIterationEndDate = resource.Project_Resources__r[previousIterationIndex].EndDate__c;

                        if(previousIterationEndDate.daysBetween(iterationStartDate) >= 1 || iterationEndDate.daysBetween(endDate) >= 1){
                            if(resourcesByRole.containsKey(resource.Role__c)){
                                resourcesByRole.get(resource.Role__c).add(resource);
                            } else{
                                resourcesByRole.put(resource.Role__c, new List<User>{resource});
                            }
                        }
                    }
                }
            }
        }

        return resourcesByRole;
    }
}